// TEST OPTION
POST http://localhost:3000/api/options/addOption
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTUyYWFiODMwMmQzNTcwNTU0M2NhMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczODg3Nzc3OSwiZXhwIjoxNzM4ODgxMzc5fQ.5p4e4g7WBxflavZ68mjPFqlHFsoLga5DbuyXS44Op-0

{
  "optionType": "options",
  "newOption": {
    "name": "supercooloption",
    "price": 1,
    "color": "#2929292",
    "pictureUrl": "ddd",
    "optionId": "5f9f4b3b1f1b431f3c1b3b1b"
  }
}