// TEST SECURE ROUTE
GET http://localhost:5001/api/options/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTUyYWFiODMwMmQzNTcwNTU0M2NhMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczODg3Nzc3OSwiZXhwIjoxNzM4ODgxMzc5fQ.5p4e4g7WBxflavZ68mjPFqlHFsoLga5DbuyXS44Op-0