services:
  web:
    build:
      context: .
      dockerfile: ./DockerFile
    container_name: app
    ports:
      - "5173:5173"
    networks:
      - app-network
    volumes:
      - ./src:/home/node/app/src # Montage du code source local
    environment:
      - CONSUMER_KEY=${CONSUMER_KEY}

networks:
  app-network:
