services:
  web:
    build:
      context: .
      dockerfile: ./DockerFile
    container_name: app
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./src:/home/node/app/src # Montage du code source local

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

networks:
  app-network:

volumes:
  mongo-data: