function createShell(image, couleur) {
  return { image, couleur };
}
const databaseShellB = [
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_BLACK0027.jpg",
    "Black"
  ),
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_CLEARBLACK0027.jpg",
    "Clear_Black"
  ),
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_CLEARBLUE0027.jpg",
    "Clear_Blue"
  ),
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_CLEARGLASS0027.jpg",
    "Clear_Glass"
  ),
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_CLEARGREEN0027.jpg",
    "Clear_Green"
  ),
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_CLEARORANGE0027.jpg",
    "Clear_Orange"
  ),
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_CLEARRED0027.jpg",
    "Clear_Red"
  ),
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_CLEARVIOLET0027.jpg",
    "Clear_Violet"
  ),
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_CLEARVIOLET-02.jpg",
    "Clear_Violet1"
  ),
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_GHOST0027.jpg",
    "Ghost"
  ),
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_ROSE0027.jpg",
    "Rose"
  ),
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_SPECIAL0027.jpg",
    "Special"
  ),
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_TURQUOISE0027.jpg",
    "Turquoise"
  ),
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_WHITE0027.jpg",
    "White"
  ),
  createShell(
    "./public/GBA/Front/GBA-Back-GBA_SHELL_BACK_YELLOW0027.jpg",
    "Yellow"
  ),
];

export default databaseShellB;
